# Generated by Django 3.2.3 on 2021-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccine_pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=7)),
                ('date', models.DateField()),
            ],
        ),
    ]
