# Generated by Django 3.2.3 on 2021-06-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vaccine_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_pincode',
            name='date',
            field=models.DateField(default='0000000', editable=False, max_length=7),
        ),
    ]
