# Generated by Django 3.2.3 on 2021-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_vaccine_pincode_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_pincode',
            name='date',
            field=models.DateField(),
        ),
    ]
